apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocdproject
  name: argocdrocks-app
spec:
  project: argocdinc-project
  source:
    repoURL: https://github.com/dk2la/sjakku.git
    targetRevision: master
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
