apiVersion: v1
kind: Service
metadata:
  name: app-will-port
spec:
  type: NodePort
  selector:
    app: app-will
  ports:
    - port: 8888
      name: http
      targetPort: 8888
      nodePort: 30011