apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: abobaproject
  name: aboba-app
spec:
  project: aboba-project
  source:
    repoURL: http://192.168.0.107:30008/root/aboba.git
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
