apiVersion: v1
kind: Service
metadata:
  name: argocd-server-port
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30010