apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  type: NodePort
  selector:
    app: gitlab-deploy
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30007
    - port: 443
      name: https
      targetPort: 443
      nodePort: 30008
    - port: 22
      name: ssh
      targetPort: 22
      nodePort: 30009

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deploy
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab-deploy
    spec:
      containers:
      - image: gitlab/gitlab-ee:latest
        name: gitlab-deploy
        resources:
          limits:
            memory: '2048Mi'
            cpu: '1000m'
          requests:
            memory: '2048Mi'
            cpu: '0.5'
        ports:
        - containerPort: 8080
        - containerPort: 443
        - containerPort: 22
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://172.18.0.3'