apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  type: NodePort
  selector:
    app: webservice
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30007
    - port: 8181
      name: https
      targetPort: 8181
      nodePort: 30008