Vagrant.configure(2) do |config|
    # [...]
    config.vm.box = "centos/8"
    config.vm.synced_folder ".", "/vagrant"
    # config.vm.box_url = ""

    config.vm.define "sjakkuS" do |control|
        control.vm.hostname = "sjakkuS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "sjakkuS"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", inline: <<-SHELL
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --flannel-iface=eth1" K3S_TOKEN=hyinya K3S_KUBECONFIG_MODE="644" sh -
            # sh /vagrant/scripts/apply-deployments.sh
        SHELL
            control.vm.provision "shell", path: "/Users/danila/Desktop/inception-of-aboba/p2/scripts/apply-deployments.sh"
    end
end