Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"
    config.vm.synced_folder ".", "/vagrant"

    config.vm.define "sjakkuS" do |control|
        control.vm.hostname = "sjakkuSp2"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "sjakkuSp2"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", path: "/Users/danila/Desktop/inception-of-aboba/p2/scripts/start.sh"
    end
end