Vagrant.configure(2) do |config|
    # [...]
    config.vm.box = "centos/8"
    # config.vm.box_url = ""

    config.vm.define "sjakkuS" do |control|
        control.vm.hostname = "sjakkuS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "sjakkuS"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", inline: <<-SHELL
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --flannel-iface=eth1" K3S_TOKEN=hyinya K3S_KUBECONFIG_MODE="644" sh -
        SHELL
            # control.vm.provision "shell", path: "path to script from host"
    end
end

Vagrant.configure(2) do |config|
    # [...]
    config.vm.box = "centos/8"
    # config.vm.box_url = ""

    config.vm.define "sjakkuSW" do |control|
        control.vm.hostname = "sjakkuSW"
        control.vm.network "private_network", ip: "192.168.42.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--name", "sjakkuSW"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "shell", inline: <<-SHELL
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --flannel-iface=eth1" K3S_URL=https://192.168.42.110:6443 K3S_TOKEN=hyinya sh -
        SHELL
            # control.vm.provision "shell", path: "path to script from host "
    end
end