Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"
    config.vm.synced_folder ".", "/vagrant"
    config.disksize.size = '30GB'

    config.vm.define "sjakkuS" do |control|
        control.vm.hostname = "sjakkuS"
        control.vm.network "public_network"
        # control.vm.network "public_network", bridge: [
        #     "en0: Wi-Fi (AirPort)",    
        #     "en1: Wi-Fi (AirPort)",
        # ]
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "sjakkuS"]
            v.memory = 4096
            v.cpus = 2
        end
        control.vm.provision "shell", path: "./scripts/disk_prepare.sh"
        control.vm.provision "shell", path: "./scripts/script.sh"
    end
end