Vagrant.configure(2) do |config|
    # [...]
    config.vm.box = "centos/8"
    config.vm.synced_folder ".", "/vagrant"
    # config.vm.box_url = ""

    config.vm.define "sjakkuS" do |control|
        control.vm.hostname = "sjakkuS"
        control.vm.network "public_network", bridge: [
            "en0: Wi-Fi (AirPort)",    
            "en1: Wi-Fi (AirPort)",
        ]
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "sjakkuS"]
            v.memory = 2048
            v.cpus = 1
        end
        # control.vm.provision "shell", inline: <<-SHELL
        # SHELL
            # control.vm.provision "shell", path: "/Users/danila/Desktop/inception-of-aboba/p2/scripts/apply-deployments.sh"
    end
end